const EXCAHGE_RATE=105; 
const YEAR_OF_DELIVERY=2022;
const SLIDE_TIME=5000;
const ARRAY_DELIVERY=[
  `03.${YEAR_OF_DELIVERY}`,
  `06.${YEAR_OF_DELIVERY}`,
  `09.${YEAR_OF_DELIVERY}`,
  `12.${YEAR_OF_DELIVERY}`
];

export {EXCAHGE_RATE,YEAR_OF_DELIVERY,SLIDE_TIME,ARRAY_DELIVERY}